name: Build and publish AAR to Maven Central

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2


    - name: Decode
      run: |
        echo "plain multiline secret"
        echo "${{secrets.TEST_SECRET_MULTILINE}}"
        echo "multiline secret base 64"
        echo "${{secrets.TEST_SECRET_MULTILINE_B64}}"
        echo "decoded multiline secret"
        mkdir -p $HOME/.gradle
        echo "${{secrets.TEST_SECRET_MULTILINE_B64}}" > $HOME/.gradle/secring.gpg.b64
        base64 -d $HOME/.gradle/secring.gpg.b64 > $HOME/.gradle/secring.gpg
        echo "print secring"
        cat $HOME/.gradle/secring.gpg
        echo "print finished"

