name: Build and publish AAR to Maven Central

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Prepare GPG key
      run: |
        set -x
        pwd
        cd ${{runner.workspace}}/ramses-android/android/ramses-aar
        pwd
        echo "${{secrets.OSSRH_GPG_SECRET_KEY}}" > secring.gpg.b64
        base64 -d secring.gpg.b64 > secring.gpg

    - name: Execute Gradle build
      run: ./android/gradlew -p ./android :ramses-aar:build

    - name: Publish Library
      run: |
        echo "Publishing aar package..."
        echo "Signing key id: $SIGNING_KEY_ID"
        ./android/gradlew -p ./android :ramses-aar:publish -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} -Psigning.password=${{ secrets.OSSRH_PASSWORD }} -Psigning.secretKeyRingFile=secring.gpg --no-daemon --no-parallel
        echo "Releasing aar package..."
        ./android/gradlew -p ./android closeAndReleaseRepository
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}

