name: Build and publish AAR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build and publish AAR
      run: ./android/gradlew -p ./android :ramses-aar:build && ./android/gradlew -p ./android publish
      env:
        GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

